steps:
  - label: ":cloudfoundry: $BUILDKITE_BRANCH"
    concurrency: 1
    concurrency_group: "blog-cf-push-branch-${BUILDKITE_BRANCH}"
    plugins:
      seek-oss/aws-sm#v2.0.0:
        env:
          CF_PASSWORD: arn:aws:secretsmanager:us-east-1:868593321044:secret:pipelines/pws/drnic/cf-password-dUL5fd
      starkandwayne/cloudfoundry-deploy#v0.9.2:
        api: https://api.run.pivotal.io
        username: drnic@starkandwayne.com
        organization: starkandwayne
        appname: "ghost-branch-${BUILDKITE_BRANCH}"
        space: blog-staging
        manifest_path: manifest-pr.yml
        vars: |
          appname: "ghost-branch-${BUILDKITE_BRANCH}"
          route-subdomain: "starkandwayne-blog-branch-${BUILDKITE_BRANCH}"
