language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '8'
  - '10'
install:
  - yarn install --ignore-engines
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
